require('../test/login_test')
require('../test/multiCountryCatalog/geoguardCheck')
require('../test/multiCountryCatalog/playlistRoot')
require('../test/multiCountryCatalog/playlistIdByLanguage')
require('../test/playground_test.js')
